### ISSUE TITLE
Path to vagrant is fixed at /usr/local/bin/vagrant

### ISSUE THREAD

**Issue by bdellegrazie** [barkingiguana/compound#1]
Hi,

For Linux systems or other systems where vagrant is installed via a package manager the path to vagrant is usually accessible by `/usr/bin/env vagrant`
This *should* work on Mac too (but I can't verify)

Can we either make the location of vagrant configurable?

Thanks!

**Comment by craigw** [comment]
Just published 0.1.14 which should fix the issue, by removing the hard coded path and relying on the environment - should use `$PATH`.
